version: '3.9'
services:

  db: 
    image: mysql:5.7.22
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3307:3306'

  api: 
    container_name: api
    build: 
      context: ./nest-admin-dashboard
    ports: 
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db
  
  web: 
    container_name: web
    build:
      context: ./client
    ports: 
      - '4000:3000'
    depends_on:
      - api

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: 
      - '8082:80'
    environment: 
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      
volumes: 
  .dbdata:


